### ISSUE TITLE
LINCD tutorial: Multiple versions of LINCD are loaded error 

### ISSUE THREAD

**Issue by rickvannierop** [Semantu/lincd#1]
As a LINCD beginner I want to complete the LINCD tutorial at https://docs.lincd.org/docs/tutorial-linked-data/ so that I can start learning to build on the platform. I get this error when I follow the instructions under the 'start development' section. Can you help me with this? Thanks in advance! Rick
 
My node version: v16.17.0

```
rickvannierop in ~/RickTest  > npm start

> RickTest@0.1.0 start
> npm run server:dev


> RickTest@0.1.0 server:dev
> env-cmd -e dev nodemon --watch ../../modules/lincd-server/lib --watch ../../modules/lincd-server/site.webpack.config.js ./backend/server.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): ../../modules/lincd-server/lib ../../modules/lincd-server/site.webpack.config.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./backend/server.js`
/Users/rickvannierop/RickTest/node_modules/lincd-jsonld/node_modules/lincd/lib/utils/Module.js:289
        throw new Error("Multiple versions of LINCD are loaded");
        ^

Error: Multiple versions of LINCD are loaded
    at initTree (/Users/rickvannierop/RickTest/node_modules/lincd-jsonld/node_modules/lincd/lib/utils/Module.js:289:15)
    at Object.<anonymous> (/Users/rickvannierop/RickTest/node_modules/lincd-jsonld/node_modules/lincd/lib/utils/Module.js:307:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/rickvannierop/RickTest/node_modules/lincd-jsonld/lib/package.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
[nodemon] app crashed - waiting for file changes before starting...
^C
rickvannierop in ~/RickTest  > npm list                         
RickTest@0.1.0 /Users/rickvannierop/RickTest
├── @babel/cli@7.20.7
├── @babel/core@7.20.7
├── @babel/plugin-transform-runtime@7.19.6
├── @babel/preset-env@7.20.2
├── @babel/preset-react@7.18.6
├── @babel/preset-typescript@7.18.6
├── @babel/register@7.18.9
├── @types/react-dom@18.0.10
├── @types/react@18.0.26
├── env-cmd@10.1.0
├── lincd-cli@0.2.1
├── lincd-jsonld@0.1.8
├── lincd-server@0.1.14
├── lincd@0.4.1
├── nodemon@2.0.20
├── react-dom@18.2.0
├── react-error-boundary@3.1.4
├── react-router-dom@6.6.1
└── react@18.2.0

rickvannierop in ~/RickTest  > 
```

**Comment by flyon** [comment]
thanks for the heads up. This is fixed now with `lincd-cli@0.2.5`

try 
```
npx lincd-cli@latest create-app test
```

and it should work just fine now
